/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlksk57.Form;
import static qlksk57.MyConnection.getConnection;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.Statement;
import java.util.ArrayList;

import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import org.apache.commons.lang3.StringUtils;

import qlksk57.control.HoaDonControl;
import qlksk57.control.NhanVienControl;
import qlksk57.control.PhongControl;
import qlksk57.models.DichVu;
import qlksk57.models.HoaDon;
import qlksk57.models.NhanVien;
import qlksk57.models.Phong;
/**
 *
 * @author khoa
 */
@SuppressWarnings("serial")
public class hoadonform extends javax.swing.JFrame {

	HoaDonControl hoaDonControl = new HoaDonControl();
	NhanVienControl nhanVienControl = new NhanVienControl();
	PhongControl phongControl = new PhongControl();
	

	ArrayList<Phong> dsphong = null;
	ArrayList<NhanVien> dsnv = null;
	
    /**
     * Creates new form hoadonform
     */
    public hoadonform() {
        initComponents();
        getConnection();
        loadComboxbo();
        hienThiDanhSachHoaDon();
        
        setLocationDefault(900, 600);
    }
    
    Connection con=null;
    Statement st=null;
    
     public void hienThiDanhSachHoaDon() {
        String colTieuDe1[] = new String[]{"Mã hóa đơn", "Mã nhân viên", "Mã phòng", "Ngày", "Giá hóa đơn"};
        ArrayList<HoaDon> dshd = hoaDonControl.layDanhSachHoaDon();

        DefaultTableModel model = new DefaultTableModel(colTieuDe1, 0);

        Object[] row;

        for (int i = 0; i < dshd.size(); i++) {

            row = new Object[5];

            // GÃ�N GIÃ� TRá»Š
            row[0] = dshd.get(i).getMaHD();
            row[1] = dshd.get(i).getMaNV();
            row[2] = dshd.get(i).getMaPhong();
            row[3] = dshd.get(i).getNgay();
            row[4] = dshd.get(i).getGiaHD();

            model.addRow(row);
        }
        
        //    }catch(ArrayIndexOutOfBoundsException ex){

        jTableHOADON.setModel(model);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jTextFieldMAHD = new javax.swing.JTextField();
        jTextFieldNGAY = new javax.swing.JTextField();
        jTextFieldGIAHD = new javax.swing.JTextField();
        them4 = new javax.swing.JButton();
        sua4 = new javax.swing.JButton();
        xoa4 = new javax.swing.JButton();
        thoat4 = new javax.swing.JButton();
        jButtonclear4 = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableHOADON = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 255));

        jPanel6.setBackground(new java.awt.Color(0, 204, 255));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel31.setText("HÓA ĐƠN");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20Layout.setHorizontalGroup(
        	jPanel20Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel20Layout.createSequentialGroup()
        			.addContainerGap(38, Short.MAX_VALUE)
        			.addComponent(jLabel31, GroupLayout.PREFERRED_SIZE, 182, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
        	jPanel20Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel20Layout.createSequentialGroup()
        			.addComponent(jLabel31)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel20.setLayout(jPanel20Layout);

        jPanel21.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin hóa đơn"));

        jLabel32.setText("Mã hóa đơn");

        jLabel33.setText("Mã nhân viên");

        jLabel34.setText("Mã phòng");

        jLabel35.setText("Ngày");

        jLabel36.setText("Giá hóa đơn");

        jTextFieldMAHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMAHDActionPerformed(evt);
            }
        });

        them4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlksk57/Form/hinh/THEM.png"))); // NOI18N
        them4.setText("Thêm");
        them4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                them4ActionPerformed(evt);
            }
        });

        sua4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlksk57/Form/hinh/SUA.png"))); // NOI18N
        sua4.setText("Sửa");
        sua4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sua4ActionPerformed(evt);
            }
        });

        xoa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlksk57/Form/hinh/XOA.png"))); // NOI18N
        xoa4.setText("Xóa");
        xoa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoa4ActionPerformed(evt);
            }
        });

        thoat4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlksk57/Form/hinh/THOAT.png"))); // NOI18N
        thoat4.setText("Thoát");
        thoat4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoat4ActionPerformed(evt);
            }
        });

        jButtonclear4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlksk57/Form/hinh/CLEAR.png"))); // NOI18N
        jButtonclear4.setText("Clear");
        jButtonclear4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonclear4ActionPerformed(evt);
            }
        });
        
        comboBoxMANVHD = new JComboBox();
        
        comboBoxMAPHONGHD = new JComboBox();

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21Layout.setHorizontalGroup(
        	jPanel21Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel21Layout.createSequentialGroup()
        			.addGap(23)
        			.addGroup(jPanel21Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel32)
        				.addComponent(jLabel33)
        				.addComponent(jLabel34)
        				.addComponent(jLabel35)
        				.addComponent(jLabel36)
        				.addGroup(jPanel21Layout.createParallelGroup(Alignment.TRAILING, false)
        					.addComponent(xoa4, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(them4, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        			.addGroup(jPanel21Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel21Layout.createSequentialGroup()
        					.addGap(13)
        					.addComponent(sua4)
        					.addGap(18)
        					.addComponent(jButtonclear4))
        				.addGroup(jPanel21Layout.createSequentialGroup()
        					.addGap(40)
        					.addGroup(jPanel21Layout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(jTextFieldGIAHD, GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        						.addComponent(jTextFieldNGAY)
        						.addComponent(jTextFieldMAHD)
        						.addComponent(comboBoxMANVHD, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(comboBoxMAPHONGHD, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        				.addGroup(jPanel21Layout.createSequentialGroup()
        					.addGap(32)
        					.addComponent(thoat4)))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
        	jPanel21Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel21Layout.createSequentialGroup()
        			.addGap(26)
        			.addGroup(jPanel21Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel32)
        				.addComponent(jTextFieldMAHD, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel21Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jLabel33)
        				.addComponent(comboBoxMANVHD, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(12)
        			.addGroup(jPanel21Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel34)
        				.addComponent(comboBoxMAPHONGHD, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(12)
        			.addGroup(jPanel21Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel35)
        				.addComponent(jTextFieldNGAY, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel21Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel36)
        				.addComponent(jTextFieldGIAHD, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(34)
        			.addGroup(jPanel21Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(them4)
        				.addComponent(sua4)
        				.addComponent(jButtonclear4))
        			.addGap(26)
        			.addGroup(jPanel21Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(xoa4)
        				.addComponent(thoat4))
        			.addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel21.setLayout(jPanel21Layout);

        jTableHOADON.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableHOADON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableHOADONMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTableHOADON);

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22Layout.setHorizontalGroup(
        	jPanel22Layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jScrollPane5, GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
        	jPanel22Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel22Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jScrollPane5, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        			.addContainerGap())
        );
        jPanel22.setLayout(jPanel22Layout);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6Layout.setHorizontalGroup(
        	jPanel6Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel6Layout.createSequentialGroup()
        			.addGroup(jPanel6Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel6Layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(jPanel21, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(jPanel22, GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE))
        				.addGroup(jPanel6Layout.createSequentialGroup()
        					.addGap(385)
        					.addComponent(jPanel20, GroupLayout.PREFERRED_SIZE, 230, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
        	jPanel6Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel6Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel20, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
        			.addGap(28)
        			.addGroup(jPanel6Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jPanel21, GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        				.addComponent(jPanel22, GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE))
        			.addContainerGap())
        );
        jPanel6.setLayout(jPanel6Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel6, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel6, GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldMAHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMAHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMAHDActionPerformed

    private void them4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_them4ActionPerformed

    	if (StringUtils.isEmpty(jTextFieldMAHD.getText()) || StringUtils.isEmpty(jTextFieldGIAHD.getText())) {
			JOptionPane.showMessageDialog(this, "Vui lòng kiểm tra Mã hóa đơn, Giá");
			return;
		}
    	
    	String maNV = ((NhanVien)comboBoxMANVHD.getSelectedObjects()[0]).getMaNV();
		String maPhong = ((Phong)comboBoxMAPHONGHD.getSelectedObjects()[0]).getMaPhong();
		
		
    	Connection con = getConnection();
        try {
            st = (Statement) con.createStatement();
            String query = "INSERT INTO hoadon(MAHD,MANV, MAPHONG, NGAY, GIAHD) VALUES('" + jTextFieldMAHD.getText() + "',"
            + "'" + maNV + "','" + maPhong + "', '" + jTextFieldNGAY.getText() + "', '" + jTextFieldGIAHD.getText() + "')";

            st.execute(query);
            hienThiDanhSachHoaDon();

        } catch (Exception ex) {
        	System.out.println(ex.getMessage());
			JOptionPane.showMessageDialog(this, ex.getMessage());
			
//            ex.printStackTrace();
        }

    }//GEN-LAST:event_them4ActionPerformed

    private void sua4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sua4ActionPerformed

    	if (jTableHOADON.getSelectedRow()==-1) {
            if (jTableHOADON.getRowCount()==0) {
                // lblError.setText("Table is empty");
            }
            else{
                //  lblError.setText("You must select a Tennis Player");
            }
        }
        else{
            DefaultTableModel model = (DefaultTableModel) jTableHOADON.getModel();
            model.setValueAt(jTextFieldMAHD.getText(), jTableHOADON.getSelectedRow(), 0);
//            model.setValueAt(jTextFieldMANVHD.getText().toString(), jTableHOADON.getSelectedRow(), 1);
//            model.setValueAt(jTextFieldMAPHONGHD.getText(), jTableHOADON.getSelectedRow(), 2);
            model.setValueAt(jTextFieldNGAY.getText(), jTableHOADON.getSelectedRow(), 3);
            model.setValueAt(jTextFieldGIAHD.getText(), jTableHOADON.getSelectedRow(), 4);

            if (StringUtils.isEmpty(jTextFieldMAHD.getText()) || StringUtils.isEmpty(jTextFieldGIAHD.getText())) {
    			JOptionPane.showMessageDialog(this, "Vui lòng kiểm tra Mã hóa đơn, Giá");
    			return;
    		}
        	
        	String maNV = ((NhanVien)comboBoxMANVHD.getSelectedObjects()[0]).getMaNV();
    		String maPhong = ((Phong)comboBoxMAPHONGHD.getSelectedObjects()[0]).getMaPhong();
    		
            
            Connection con = getConnection();
            try {
                // Táº¡o má»™t Ä‘á»‘i tÆ°á»£ng Ä‘á»ƒ thá»±c hiá»‡n cÃ´ng viá»‡c
                st = (Statement) con.createStatement();
                String query = String.format("UPDATE HoaDon SET MANV ='%s', MAPHONG = '%s' , NGAY = '%s', GIAHD = %s WHERE MAHD = '%s'", maNV,
                		maPhong,jTextFieldNGAY.getText(),
						jTextFieldGIAHD.getText(), jTextFieldMAHD.getText()); 
            	System.out.println("sql : " + query);
                st.execute(query);
                hienThiDanhSachHoaDon();

            } catch (Exception ex) {
            	System.out.println(ex.getMessage());
    			JOptionPane.showMessageDialog(this, ex.getMessage());
    			
//                ex.printStackTrace();
            }
        }

    }//GEN-LAST:event_sua4ActionPerformed

    private void xoa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoa4ActionPerformed

    	if (StringUtils.isEmpty(jTextFieldMAHD.getText())) {
			JOptionPane.showMessageDialog(this, "Vui lòng kiểm tra Mã hóa đơn, Giá");
			return;
		}
    	
    	
    	Connection con = getConnection();
        try {
            // Táº¡o má»™t Ä‘á»‘i tÆ°á»£ng Ä‘á»ƒ thá»±c hiá»‡n cÃ´ng viá»‡c
            st = (Statement) con.createStatement();
            String query = "DELETE FROM hoadon WHERE MAHD = '" + jTextFieldMAHD.getText() + "'";
            st.executeUpdate(query);
            hienThiDanhSachHoaDon();

        } catch (Exception ex) {
        	System.out.println(ex.getMessage());
			JOptionPane.showMessageDialog(this, ex.getMessage());
			
//            ex.printStackTrace();
        }
    }//GEN-LAST:event_xoa4ActionPerformed

    private void thoat4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoat4ActionPerformed
        // TODO add your handling code here:
        thoat4.setToolTipText("Click vào thoát chương trình ");
        int selected = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thoát chương trình"
            + " trên không", "Thông báo", JOptionPane.YES_NO_CANCEL_OPTION);
        if (selected == JOptionPane.YES_NO_OPTION) {
            this.dispose();

        }
    }//GEN-LAST:event_thoat4ActionPerformed

    private void jButtonclear4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonclear4ActionPerformed
        // TODO add your handling code here:
        setEmptyAll();
        jTextFieldMAHD.requestFocus();

    }//GEN-LAST:event_jButtonclear4ActionPerformed

    private void jTableHOADONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableHOADONMouseClicked
        // TODO add your handling code here:
        int i = jTableHOADON.getSelectedRow();
        TableModel model = jTableHOADON.getModel();
        jTextFieldMAHD.setText(model.getValueAt(i, 0).toString());
        

		String maNV = model.getValueAt(i, 1).toString();
		String maPhong = model.getValueAt(i, 2).toString();

		int index = 0;
		for (NhanVien nv : dsnv) {
			if (nv.getMaNV().equals(maNV)) {
				break;
			}
			index++;
		}		
		comboBoxMANVHD.setSelectedIndex(index);
		
		index = 0;
		for (Phong phong : dsphong) {
			if (phong.getMaPhong().equals(maPhong)) {
				break;
			}
			index++;
		}		
		comboBoxMAPHONGHD.setSelectedIndex(index);

        
        jTextFieldNGAY.setText(model.getValueAt(i, 3).toString());
        jTextFieldGIAHD.setText(model.getValueAt(i, 4).toString());
    }//GEN-LAST:event_jTableHOADONMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hoadonform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hoadonform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hoadonform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hoadonform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hoadonform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonclear4;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTableHOADON;
    private javax.swing.JTextField jTextFieldGIAHD;
    private javax.swing.JTextField jTextFieldMAHD;
    private javax.swing.JTextField jTextFieldNGAY;
    private javax.swing.JButton sua4;
    private javax.swing.JButton them4;
    private javax.swing.JButton thoat4;
    private javax.swing.JButton xoa4;
    private JComboBox comboBoxMANVHD;
    private JComboBox comboBoxMAPHONGHD;
    // End of variables declaration//GEN-END:variables
    
	@SuppressWarnings("unchecked")
	private void loadComboxbo() {
		dsphong = phongControl.layDanhSachNotEmpty();
		dsnv = nhanVienControl.layDanhSachNhanVien();

		DefaultComboBoxModel<Phong> comboBoxModelPhong = new DefaultComboBoxModel<>(
				dsphong.toArray(new Phong[dsphong.size()]));
		comboBoxMAPHONGHD.setModel(comboBoxModelPhong);

		DefaultComboBoxModel<NhanVien> comboBoxModelNVHD = new DefaultComboBoxModel<>(
				dsnv.toArray(new NhanVien[dsnv.size()]));
		comboBoxMANVHD.setModel(comboBoxModelNVHD);

	}
	

	private void setEmptyAll() {
		jTextFieldMAHD.setText("");
        jTextFieldNGAY.setText("");
        jTextFieldGIAHD.setText("");
		comboBoxMANVHD.setSelectedIndex(0);
		comboBoxMAPHONGHD.setSelectedIndex(0);
	}

	private void setLocationDefault(int w, int h) {
		Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

		int x = (dim.width - w) / 2;
		int y = (dim.height - h) / 2;

		// Move the window
		this.setLocation(x, y);
	}
    
}
