/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlksk57.Form;

import static qlksk57.MyConnection.getConnection;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;

import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import qlksk57.KhachHang;

/**
 *
 * @author khoa
 */
@SuppressWarnings("serial")
public class khachhangform extends JFrame {

	/**
	 * Creates new form khachhangform
	 */
	public khachhangform() {
		initComponents();
		getConnection();
		hienThiDanhSachKhachHang();
	}

	Connection con = null;
	Statement st = null;

	public ArrayList<KhachHang> layDanhSachKhachHang() {
		ArrayList<KhachHang> dskh = new ArrayList<KhachHang>();
		Connection con = getConnection();
		try {
			st = (Statement) con.createStatement();
			String sql = "SELECT * FROM khachhang";
			// ThÆ°cj thi cÃ¢u lá»‡nh truy váº¥n
			ResultSet rs = st.executeQuery(sql);

			KhachHang kh;
			while (rs.next()) {
				kh = new KhachHang(rs.getString("MAKH"), rs.getString("TENKH"), rs.getString("CMND"),
						rs.getString("QUOCTICH"), rs.getString("GIOITINH"), rs.getInt("TUOI"), rs.getString("SDT"),
						rs.getString("MAPHONG"));

				// ThÃªm vÃ o danh sÃ¡ch
				dskh.add(kh);
			}
		} catch (Exception ex) {
			ex.printStackTrace();

		}
		return dskh;
	}

	public void hienThiDanhSachKhachHang() {
		String colTieuDe1[] = new String[] { "Mã khách hàng", "Tên khách hàng", "Chứng minh nhân dân", "Quốc tịch",
				"Giới tính", "Tuổi", "Số điện thoại", "Mã phòng" };
		ArrayList<KhachHang> dskh = layDanhSachKhachHang();

		DefaultTableModel model = new DefaultTableModel(colTieuDe1, 0);

		Object[] row;

		for (int i = 0; i < dskh.size(); i++) {

			row = new Object[8];

			// GÃ�N GIÃ� TRá»Š
			row[0] = dskh.get(i).getMaKH();
			row[1] = dskh.get(i).getTenKH();
			row[2] = dskh.get(i).getCmnd();
			row[3] = dskh.get(i).getQuocTich();
			row[4] = dskh.get(i).getGioiTinh();
			row[5] = dskh.get(i).getTuoi();
			row[6] = dskh.get(i).getSdt();
			row[7] = dskh.get(i).getMaPhong();

			model.addRow(row);
		}

		// }catch(ArrayIndexOutOfBoundsException ex){

		jTableKhachhang.setModel(model);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel4 = new JPanel();
		jPanel12 = new JPanel();
		jLabel10 = new JLabel();
		jLabel11 = new JLabel();
		jLabel12 = new JLabel();
		jLabel13 = new JLabel();
		jLabel14 = new JLabel();
		jLabel15 = new JLabel();
		jLabel16 = new JLabel();
		jLabel17 = new JLabel();
		jTextFieldMAKH = new JTextField();
		jTextFieldTENKH = new JTextField();
		jTextFieldCMND = new JTextField();
		jTextFieldQUOCTICH = new JTextField();
		jTextFieldGIOITINHKH = new JTextField();
		jTextFieldTUOI = new JTextField();
		jTextFieldSDT = new JTextField();
		jTextFieldMAPHONGKH = new JTextField();
		them1 = new JButton();
		sua1 = new JButton();
		xoa1 = new JButton();
		thoat1 = new JButton();
		jButtonclear2 = new JButton();
		jPanel11 = new JPanel();
		jLabel9 = new JLabel();
		jScrollPane2 = new JScrollPane();
		jTableKhachhang = new JTable();

		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

		jPanel4.setBackground(new java.awt.Color(0, 204, 255));

		jPanel12.setBorder(BorderFactory.createTitledBorder("Thông tin khách hàng"));

		jLabel10.setText("Mã khách hàng");

		jLabel11.setText("Tên khách hàng");

		jLabel12.setText("Chứng minh nhân dân");

		jLabel13.setText("Quốc tịch");

		jLabel14.setText("Giới tính");

		jLabel15.setText("Tuổi ");

		jLabel16.setText("Số điện thoại");

		jLabel17.setText("Mã phòng");

		jTextFieldMAKH.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldMAKHActionPerformed(evt);
			}
		});

		jTextFieldTENKH.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldTENKHActionPerformed(evt);
			}
		});

		jTextFieldMAPHONGKH.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldMAPHONGKHActionPerformed(evt);
			}
		});

		them1.setIcon(new ImageIcon(getClass().getResource("/qlksk57/Form/hinh/THEM.png"))); // NOI18N
		them1.setText("Thêm");
		them1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				them1ActionPerformed(evt);
			}
		});

		sua1.setIcon(new ImageIcon(getClass().getResource("/qlksk57/Form/hinh/SUA.png"))); // NOI18N
		sua1.setText("Sửa");
		sua1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				sua1ActionPerformed(evt);
			}
		});

		xoa1.setIcon(new ImageIcon(getClass().getResource("/qlksk57/Form/hinh/XOA.png"))); // NOI18N
		xoa1.setText("Xóa");
		xoa1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				xoa1ActionPerformed(evt);
			}
		});

		thoat1.setIcon(new ImageIcon(getClass().getResource("/qlksk57/Form/hinh/THOAT.png"))); // NOI18N
		thoat1.setText("Thoát");
		thoat1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				thoat1ActionPerformed(evt);
			}
		});

		jButtonclear2.setIcon(new ImageIcon(getClass().getResource("/qlksk57/Form/hinh/CLEAR.png"))); // NOI18N
		jButtonclear2.setText("Clear");
		jButtonclear2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonclear2ActionPerformed(evt);
			}
		});

		GroupLayout jPanel12Layout = new GroupLayout(jPanel12);
		jPanel12.setLayout(jPanel12Layout);
		jPanel12Layout
				.setHorizontalGroup(
						jPanel12Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
								.addGroup(
										jPanel12Layout
												.createSequentialGroup().addGap(22, 22, 22).addGroup(jPanel12Layout
														.createParallelGroup(GroupLayout.Alignment.LEADING)
														.addGroup(jPanel12Layout.createSequentialGroup().addGroup(
																jPanel12Layout
																		.createParallelGroup(
																				GroupLayout.Alignment.LEADING, false)
																		.addComponent(them1, GroupLayout.DEFAULT_SIZE,
																				GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(xoa1, GroupLayout.DEFAULT_SIZE,
																				GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE))
																.addGap(32, 32, 32)
																.addGroup(jPanel12Layout.createParallelGroup(
																		GroupLayout.Alignment.LEADING).addComponent(
																				thoat1)
																		.addGroup(jPanel12Layout.createSequentialGroup()
																				.addComponent(sua1).addGap(18, 18, 18)
																				.addComponent(jButtonclear2))))
														.addGroup(jPanel12Layout
																.createSequentialGroup().addGroup(jPanel12Layout
																		.createParallelGroup(
																				GroupLayout.Alignment.LEADING)
																		.addComponent(jLabel10).addComponent(jLabel11)
																		.addComponent(jLabel12).addComponent(jLabel13)
																		.addComponent(jLabel14).addComponent(jLabel15)
																		.addComponent(jLabel16).addComponent(jLabel17))
																.addGap(18, 18, 18)
																.addGroup(jPanel12Layout
																		.createParallelGroup(
																				GroupLayout.Alignment.LEADING)
																		.addComponent(jTextFieldQUOCTICH,
																				GroupLayout.PREFERRED_SIZE, 84,
																				GroupLayout.PREFERRED_SIZE)
																		.addComponent(jTextFieldCMND,
																				GroupLayout.PREFERRED_SIZE, 84,
																				GroupLayout.PREFERRED_SIZE)
																		.addComponent(jTextFieldTENKH,
																				GroupLayout.PREFERRED_SIZE, 84,
																				GroupLayout.PREFERRED_SIZE)
																		.addComponent(jTextFieldMAKH,
																				GroupLayout.PREFERRED_SIZE, 84,
																				GroupLayout.PREFERRED_SIZE)
																		.addComponent(jTextFieldGIOITINHKH,
																				GroupLayout.PREFERRED_SIZE, 84,
																				GroupLayout.PREFERRED_SIZE)
																		.addComponent(jTextFieldTUOI,
																				GroupLayout.PREFERRED_SIZE, 84,
																				GroupLayout.PREFERRED_SIZE)
																		.addComponent(jTextFieldSDT,
																				GroupLayout.PREFERRED_SIZE, 84,
																				GroupLayout.PREFERRED_SIZE)
																		.addComponent(jTextFieldMAPHONGKH,
																				GroupLayout.PREFERRED_SIZE, 84,
																				GroupLayout.PREFERRED_SIZE))))
												.addContainerGap(36, Short.MAX_VALUE)));
		jPanel12Layout.setVerticalGroup(jPanel12Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(jPanel12Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel12Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel10).addComponent(jTextFieldMAKH, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel12Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel11).addComponent(jTextFieldTENKH, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel12Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel12).addComponent(jTextFieldCMND, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel12Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel13).addComponent(jTextFieldQUOCTICH, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel12Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel14).addComponent(jTextFieldGIOITINHKH, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel12Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel15).addComponent(jTextFieldTUOI, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel12Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel16).addComponent(jTextFieldSDT, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jPanel12Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel17).addComponent(jTextFieldMAPHONGKH, GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addGap(41, 41, 41)
						.addGroup(jPanel12Layout.createParallelGroup(GroupLayout.Alignment.BASELINE).addComponent(them1)
								.addComponent(sua1).addComponent(jButtonclear2))
						.addGap(28, 28, 28).addGroup(jPanel12Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(xoa1).addComponent(thoat1))
						.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		jLabel9.setText("QUẢN LÍ KHÁCH HÀNG");

		GroupLayout jPanel11Layout = new GroupLayout(jPanel11);
		jPanel11.setLayout(jPanel11Layout);
		jPanel11Layout.setHorizontalGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(jPanel11Layout.createSequentialGroup().addGap(18, 18, 18)
						.addComponent(jLabel9, GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE).addContainerGap()));
		jPanel11Layout.setVerticalGroup(jPanel11Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(jPanel11Layout.createSequentialGroup().addGap(27, 27, 27)
						.addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE)
						.addContainerGap(27, Short.MAX_VALUE)));

		jTableKhachhang
				.setModel(new DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jTableKhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jTableKhachhangMouseClicked(evt);
			}
		});
		jScrollPane2.setViewportView(jTableKhachhang);

		GroupLayout jPanel4Layout = new GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addGap(36, 36, 36)
						.addComponent(jPanel12, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addGap(27, 27, 27)
						.addGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
								.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 637, GroupLayout.PREFERRED_SIZE)
								.addGroup(jPanel4Layout.createSequentialGroup().addGap(162, 162, 162).addComponent(
										jPanel11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(22, Short.MAX_VALUE)));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addGap(27, 27, 27).addGroup(jPanel4Layout
						.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addComponent(jPanel12, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addGroup(jPanel4Layout.createSequentialGroup()
								.addComponent(jPanel11, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addGap(22, 22, 22).addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 275,
										GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		GroupLayout layout = new GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGap(0, 1089, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
								.addGroup(GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup()
												.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jPanel4, GroupLayout.PREFERRED_SIZE,
														GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
												.addContainerGap())));
		layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGap(0, 461, Short.MAX_VALUE)
				.addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addGroup(
						GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup().addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jTextFieldMAKHActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldMAKHActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextFieldMAKHActionPerformed

	private void jTextFieldTENKHActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldTENKHActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextFieldTENKHActionPerformed

	private void jTextFieldMAPHONGKHActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldMAPHONGKHActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextFieldMAPHONGKHActionPerformed

	private void them1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_them1ActionPerformed
		// TODO add your handling code here:
		Connection con = getConnection();
		try {
			// Táº¡o má»™t Ä‘á»‘i tÆ°á»£ng Ä‘á»ƒ thá»±c hiá»‡n cÃ´ng viá»‡c
			st = (Statement) con.createStatement();
			String query = "INSERT INTO khachhang(MAKH,TENKH, CMND, QUOCTICH, GIOITINH, TUOI, SDT, MAPHONG) VALUES('"
					+ jTextFieldMAKH.getText() + "'," + "'" + jTextFieldTENKH.getText() + "','"
					+ jTextFieldCMND.getText() + "', '" + jTextFieldQUOCTICH.getText() + "', '"
					+ jTextFieldGIOITINHKH.getText() + "', '" + jTextFieldTUOI.getText() + "', '"
					+ jTextFieldSDT.getText() + "', '" + jTextFieldMAPHONGKH.getText() + "')";

			st.execute(query);
			hienThiDanhSachKhachHang();

		} catch (Exception ex) {
			ex.printStackTrace();
		}

	}// GEN-LAST:event_them1ActionPerformed

	private void sua1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_sua1ActionPerformed
		// TODO add your handling code here:
		if (jTableKhachhang.getSelectedRow() == -1) {
			if (jTableKhachhang.getRowCount() == 0) {
				// lblError.setText("Table is empty");
			} else {
				// lblError.setText("You must select a Tennis Player");
			}
		} else {
			DefaultTableModel model = (DefaultTableModel) jTableKhachhang.getModel();
			model.setValueAt(jTextFieldMAKH.getText(), jTableKhachhang.getSelectedRow(), 0);
			model.setValueAt(jTextFieldTENKH.getText().toString(), jTableKhachhang.getSelectedRow(), 1);
			model.setValueAt(jTextFieldCMND.getText(), jTableKhachhang.getSelectedRow(), 2);
			model.setValueAt(jTextFieldQUOCTICH.getText(), jTableKhachhang.getSelectedRow(), 3);
			model.setValueAt(jTextFieldGIOITINHKH.getText(), jTableKhachhang.getSelectedRow(), 4);
			model.setValueAt(jTextFieldTUOI.getText(), jTableKhachhang.getSelectedRow(), 5);
			model.setValueAt(jTextFieldSDT.getText(), jTableKhachhang.getSelectedRow(), 6);
			model.setValueAt(jTextFieldMAPHONGKH.getText(), jTableKhachhang.getSelectedRow(), 7);
		}
	}// GEN-LAST:event_sua1ActionPerformed

	private void xoa1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_xoa1ActionPerformed
		// TODO add your handling code here:
		Connection con = getConnection();
		try {
			// Táº¡o má»™t Ä‘á»‘i tÆ°á»£ng Ä‘á»ƒ thá»±c hiá»‡n cÃ´ng viá»‡c
			st = (Statement) con.createStatement();
			String query = "DELETE FROM khachhang WHERE MAKH = '" + jTextFieldMAKH.getText() + "'";
			st.executeUpdate(query);
			hienThiDanhSachKhachHang();

		} catch (Exception ex) {

			ex.printStackTrace();
		}
	}// GEN-LAST:event_xoa1ActionPerformed

	private void thoat1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_thoat1ActionPerformed
		// TODO add your handling code here:
		thoat1.setToolTipText("Click Ảnh để thoát chương trình");
		int selected = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thoát chương trình" + " trên không",
				"thông báo", JOptionPane.YES_NO_CANCEL_OPTION);
		if (selected == JOptionPane.YES_NO_OPTION) {
			this.dispose();

		}
	}// GEN-LAST:event_thoat1ActionPerformed

	private void jButtonclear2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonclear2ActionPerformed
		// TODO add your handling code here:
		jTextFieldMAKH.setText("");
		jTextFieldTENKH.setText("");
		jTextFieldCMND.setText("");
		jTextFieldQUOCTICH.setText("");
		jTextFieldGIOITINHKH.setText("");
		jTextFieldTUOI.setText("");
		jTextFieldSDT.setText("");
		jTextFieldMAPHONGKH.setText("");
		jTextFieldMAKH.requestFocus();

	}// GEN-LAST:event_jButtonclear2ActionPerformed

	private void jTableKhachhangMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTableKhachhangMouseClicked
		// TODO add your handling code here:
		int i = jTableKhachhang.getSelectedRow();
		TableModel model = jTableKhachhang.getModel();
		jTextFieldMAKH.setText(model.getValueAt(i, 0).toString());
		jTextFieldTENKH.setText(model.getValueAt(i, 1).toString());
		jTextFieldCMND.setText(model.getValueAt(i, 2).toString());
		jTextFieldQUOCTICH.setText(model.getValueAt(i, 3).toString());
		jTextFieldGIOITINHKH.setText(model.getValueAt(i, 4).toString());
		jTextFieldTUOI.setText(model.getValueAt(i, 5).toString());
		jTextFieldSDT.setText(model.getValueAt(i, 6).toString());
		jTextFieldMAPHONGKH.setText(model.getValueAt(i, 7).toString());
	}// GEN-LAST:event_jTableKhachhangMouseClicked

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(khachhangform.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(khachhangform.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(khachhangform.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(khachhangform.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new khachhangform().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private JButton jButtonclear2;
	private JLabel jLabel10;
	private JLabel jLabel11;
	private JLabel jLabel12;
	private JLabel jLabel13;
	private JLabel jLabel14;
	private JLabel jLabel15;
	private JLabel jLabel16;
	private JLabel jLabel17;
	private JLabel jLabel9;
	private JPanel jPanel11;
	private JPanel jPanel12;
	private JPanel jPanel4;
	private JScrollPane jScrollPane2;
	private JTable jTableKhachhang;
	private JTextField jTextFieldCMND;
	private JTextField jTextFieldGIOITINHKH;
	private JTextField jTextFieldMAKH;
	private JTextField jTextFieldMAPHONGKH;
	private JTextField jTextFieldQUOCTICH;
	private JTextField jTextFieldSDT;
	private JTextField jTextFieldTENKH;
	private JTextField jTextFieldTUOI;
	private JButton sua1;
	private JButton them1;
	private JButton thoat1;
	private JButton xoa1;
	// End of variables declaration//GEN-END:variables
}
