/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlksk57.Form;

import static qlksk57.MyConnection.getConnection;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.Statement;
import java.util.ArrayList;

import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import qlksk57.control.KhachHangControl;
import qlksk57.control.PhongControl;
import qlksk57.models.KhachHang;
import qlksk57.models.Phong;

/**
 *
 * @author khoa
 */
@SuppressWarnings("serial")
public class khachhangform extends JFrame {

	KhachHangControl khachHangControl = new KhachHangControl();
	PhongControl phongControl = new PhongControl();

	ArrayList<Phong> dsphong = null;

	/**
	 * Creates new form khachhangform
	 */
	public khachhangform() {
		setResizable(false);
		initComponents();

		getConnection();
		loadComboxbo();
		hienThiDanhSachKhachHang();
		setLocationDefault(1100, 600);
	}

	Connection con = null;
	Statement st = null;

	public void hienThiDanhSachKhachHang() {
		String colTieuDe1[] = new String[] { "Mã khách hàng", "Tên khách hàng", "Chứng minh nhân dân", "Quốc tịch",
				"Giới tính", "Tuổi", "Số điện thoại", "Mã phòng" };
		ArrayList<KhachHang> dskh = khachHangControl.layDanhSachKhachHang();

		DefaultTableModel model = new DefaultTableModel(colTieuDe1, 0);

		Object[] row;

		for (int i = 0; i < dskh.size(); i++) {

			row = new Object[8];

			// GÃ�N GIÃ� TRá»Š
			row[0] = dskh.get(i).getMaKH();
			row[1] = dskh.get(i).getTenKH();
			row[2] = dskh.get(i).getCmnd();
			row[3] = dskh.get(i).getQuocTich();
			row[4] = dskh.get(i).getGioiTinh();
			row[5] = dskh.get(i).getTuoi();
			row[6] = dskh.get(i).getSdt();
			row[7] = dskh.get(i).getMaPhong();

			model.addRow(row);
		}

		// }catch(ArrayIndexOutOfBoundsException ex){

		jTableKhachhang.setModel(model);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	@SuppressWarnings({ "unchecked", "rawtypes" })
	private void initComponents() {

		jPanel4 = new JPanel();
		jPanel12 = new JPanel();
		jLabel10 = new JLabel();
		jLabel11 = new JLabel();
		jLabel12 = new JLabel();
		jLabel13 = new JLabel();
		jLabel14 = new JLabel();
		jLabel15 = new JLabel();
		jLabel16 = new JLabel();
		jLabel17 = new JLabel();
		jTextFieldMAKH = new JTextField();
		jTextFieldTENKH = new JTextField();
		jTextFieldCMND = new JTextField();
		jTextFieldQUOCTICH = new JTextField();
		jTextFieldTUOI = new JTextField();
		jTextFieldSDT = new JTextField();
		them1 = new JButton();
		sua1 = new JButton();
		xoa1 = new JButton();
		thoat1 = new JButton();
		jButtonclear2 = new JButton();
		jPanel11 = new JPanel();
		jLabel9 = new JLabel();
		jScrollPane2 = new JScrollPane();
		jTableKhachhang = new JTable();

		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

		jPanel4.setBackground(new java.awt.Color(0, 204, 255));

		jPanel12.setBorder(BorderFactory.createTitledBorder("Thông tin khách hàng"));

		jLabel10.setText("Mã khách hàng");

		jLabel11.setText("Tên khách hàng");

		jLabel12.setText("Chứng minh nhân dân");

		jLabel13.setText("Quốc tịch");

		jLabel14.setText("Giới tính");

		jLabel15.setText("Tuổi ");

		jLabel16.setText("Số điện thoại");

		jLabel17.setText("Mã phòng");

		jTextFieldMAKH.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldMAKHActionPerformed(evt);
			}
		});

		jTextFieldTENKH.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldTENKHActionPerformed(evt);
			}
		});

		them1.setIcon(new ImageIcon(getClass().getResource("/qlksk57/Form/hinh/THEM.png"))); // NOI18N
		them1.setText("Thêm");
		them1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				them1ActionPerformed(evt);
			}
		});

		sua1.setIcon(new ImageIcon(getClass().getResource("/qlksk57/Form/hinh/SUA.png"))); // NOI18N
		sua1.setText("Sửa");
		sua1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				sua1ActionPerformed(evt);
			}
		});

		xoa1.setIcon(new ImageIcon(getClass().getResource("/qlksk57/Form/hinh/XOA.png"))); // NOI18N
		xoa1.setText("Xóa");
		xoa1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				xoa1ActionPerformed(evt);
			}
		});

		thoat1.setIcon(new ImageIcon(getClass().getResource("/qlksk57/Form/hinh/THOAT.png"))); // NOI18N
		thoat1.setText("Thoát");
		thoat1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				thoat1ActionPerformed(evt);
			}
		});

		jButtonclear2.setIcon(new ImageIcon(getClass().getResource("/qlksk57/Form/hinh/CLEAR.png"))); // NOI18N
		jButtonclear2.setText("Clear");
		jButtonclear2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonclear2ActionPerformed(evt);
			}
		});

		comboBoxMAPHONGKH = new JComboBox();
		String gender[] = { "NAM", "NỮ" };

		comboBoxGIOITINH = new JComboBox(gender);

		GroupLayout jPanel12Layout = new GroupLayout(jPanel12);
		jPanel12Layout.setHorizontalGroup(jPanel12Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel12Layout.createSequentialGroup().addGap(22)
						.addGroup(jPanel12Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel12Layout.createSequentialGroup()
										.addGroup(jPanel12Layout.createParallelGroup(Alignment.LEADING, false)
												.addComponent(xoa1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(them1))
										.addGap(18)
										.addGroup(jPanel12Layout.createParallelGroup(Alignment.LEADING, false)
												.addComponent(thoat1, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE,
														GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(sua1, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE,
														GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
										.addGap(22).addComponent(jButtonclear2).addGap(17))
								.addGroup(jPanel12Layout.createSequentialGroup().addGroup(jPanel12Layout
										.createParallelGroup(Alignment.LEADING).addComponent(jLabel10)
										.addComponent(jLabel11).addComponent(jLabel12).addComponent(jLabel13)
										.addComponent(jLabel14).addComponent(jLabel15).addComponent(jLabel16)
										.addComponent(jLabel17)).addGap(18)
										.addGroup(jPanel12Layout.createParallelGroup(Alignment.LEADING)
												.addComponent(comboBoxGIOITINH, 0, 154, Short.MAX_VALUE)
												.addComponent(comboBoxMAPHONGKH, 0, 154, Short.MAX_VALUE)
												.addComponent(jTextFieldSDT, GroupLayout.DEFAULT_SIZE, 154,
														Short.MAX_VALUE)
												.addComponent(jTextFieldTUOI, GroupLayout.DEFAULT_SIZE, 154,
														Short.MAX_VALUE)
												.addComponent(jTextFieldMAKH, GroupLayout.DEFAULT_SIZE, 154,
														Short.MAX_VALUE)
												.addComponent(jTextFieldTENKH, GroupLayout.DEFAULT_SIZE, 154,
														Short.MAX_VALUE)
												.addComponent(jTextFieldCMND, GroupLayout.DEFAULT_SIZE, 154,
														Short.MAX_VALUE)
												.addComponent(jTextFieldQUOCTICH, GroupLayout.DEFAULT_SIZE, 154,
														Short.MAX_VALUE))
										.addGap(36)))));
		jPanel12Layout.setVerticalGroup(jPanel12Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel12Layout
				.createSequentialGroup().addContainerGap()
				.addGroup(jPanel12Layout
						.createParallelGroup(Alignment.BASELINE).addComponent(jLabel10).addComponent(jTextFieldMAKH,
								GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(ComponentPlacement.UNRELATED)
				.addGroup(jPanel12Layout
						.createParallelGroup(Alignment.BASELINE).addComponent(jLabel11).addComponent(jTextFieldTENKH,
								GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(ComponentPlacement.UNRELATED)
				.addGroup(jPanel12Layout
						.createParallelGroup(Alignment.BASELINE).addComponent(jLabel12).addComponent(jTextFieldCMND,
								GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(ComponentPlacement.UNRELATED)
				.addGroup(jPanel12Layout
						.createParallelGroup(Alignment.BASELINE).addComponent(jLabel13).addComponent(jTextFieldQUOCTICH,
								GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(ComponentPlacement.UNRELATED)
				.addGroup(jPanel12Layout
						.createParallelGroup(Alignment.BASELINE).addComponent(jLabel14).addComponent(comboBoxGIOITINH,
								GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(ComponentPlacement.UNRELATED)
				.addGroup(jPanel12Layout
						.createParallelGroup(Alignment.BASELINE).addComponent(jLabel15).addComponent(jTextFieldTUOI,
								GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(ComponentPlacement.UNRELATED)
				.addGroup(jPanel12Layout
						.createParallelGroup(Alignment.BASELINE).addComponent(jLabel16).addComponent(jTextFieldSDT,
								GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(ComponentPlacement.UNRELATED)
				.addGroup(jPanel12Layout
						.createParallelGroup(Alignment.BASELINE).addComponent(jLabel17).addComponent(comboBoxMAPHONGKH,
								GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
				.addGap(18)
				.addGroup(jPanel12Layout.createParallelGroup(Alignment.BASELINE).addComponent(them1)
						.addComponent(jButtonclear2).addComponent(sua1))
				.addPreferredGap(ComponentPlacement.UNRELATED)
				.addGroup(
						jPanel12Layout.createParallelGroup(Alignment.BASELINE).addComponent(xoa1).addComponent(thoat1))
				.addGap(24)));
		jPanel12.setLayout(jPanel12Layout);

		jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		jLabel9.setText("QUẢN LÍ KHÁCH HÀNG");

		GroupLayout jPanel11Layout = new GroupLayout(jPanel11);
		jPanel11Layout.setHorizontalGroup(jPanel11Layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(Alignment.LEADING, jPanel11Layout.createSequentialGroup().addGap(14)
						.addComponent(jLabel9, GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE).addGap(14)));
		jPanel11Layout.setVerticalGroup(jPanel11Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
						.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE).addGap(7)));
		jPanel11.setLayout(jPanel11Layout);

		jTableKhachhang
				.setModel(new DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jTableKhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jTableKhachhangMouseClicked(evt);
			}
		});
		jScrollPane2.setViewportView(jTableKhachhang);

		GroupLayout gl_jPanel4 = new GroupLayout(jPanel4);
		gl_jPanel4.setHorizontalGroup(gl_jPanel4.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_jPanel4.createSequentialGroup().addGroup(gl_jPanel4.createParallelGroup(Alignment.LEADING)
						.addGroup(gl_jPanel4.createSequentialGroup().addContainerGap()
								.addComponent(jPanel12, GroupLayout.PREFERRED_SIZE, 328, GroupLayout.PREFERRED_SIZE)
								.addGap(18).addComponent(jScrollPane2, GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE))
						.addGroup(gl_jPanel4.createSequentialGroup().addGap(426).addComponent(jPanel11,
								GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
						.addContainerGap()));
		gl_jPanel4.setVerticalGroup(gl_jPanel4.createParallelGroup(Alignment.TRAILING)
				.addGroup(gl_jPanel4.createSequentialGroup().addGap(4)
						.addComponent(jPanel11, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE).addGap(11)
						.addGroup(gl_jPanel4.createParallelGroup(Alignment.LEADING)
								.addComponent(jScrollPane2, GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
								.addComponent(jPanel12, GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE))
						.addContainerGap()));
		jPanel4.setLayout(gl_jPanel4);

		GroupLayout layout = new GroupLayout(getContentPane());
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.TRAILING).addComponent(jPanel4,
				Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 1142, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.TRAILING).addComponent(jPanel4, Alignment.LEADING,
				GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE));
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jTextFieldMAKHActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldMAKHActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextFieldMAKHActionPerformed

	private void jTextFieldTENKHActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldTENKHActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextFieldTENKHActionPerformed

	private void them1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_them1ActionPerformed
		// TODO add your handling code here:

		String maPhong = ((Phong) comboBoxMAPHONGKH.getSelectedObjects()[0]).getMaPhong();

		Connection con = getConnection();
		try {
			st = (Statement) con.createStatement();
			String query = "INSERT INTO khachhang(MAKH,TENKH, CMND, QUOCTICH, GIOITINH, TUOI, SDT, MAPHONG) VALUES('"
					+ jTextFieldMAKH.getText() + "'," + "'" + jTextFieldTENKH.getText() + "','"
					+ jTextFieldCMND.getText() + "', '" + jTextFieldQUOCTICH.getText() + "', '"
					+ comboBoxGIOITINH.getSelectedItem() + "', '" + jTextFieldTUOI.getText() + "', '"
					+ jTextFieldSDT.getText() + "', '" + maPhong + "')";

			st.execute(query);
			hienThiDanhSachKhachHang();

		} catch (Exception ex) {
			ex.printStackTrace();
		}

	}// GEN-LAST:event_them1ActionPerformed

	private void sua1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_sua1ActionPerformed
		// TODO add your handling code here:
		if (jTableKhachhang.getSelectedRow() == -1) {
			if (jTableKhachhang.getRowCount() == 0) {
				// lblError.setText("Table is empty");
			} else {
				// lblError.setText("You must select a Tennis Player");
			}
		} else {
			String maPhong = ((Phong) comboBoxMAPHONGKH.getSelectedObjects()[0]).getMaPhong();

			DefaultTableModel model = (DefaultTableModel) jTableKhachhang.getModel();
			model.setValueAt(jTextFieldMAKH.getText(), jTableKhachhang.getSelectedRow(), 0);
			model.setValueAt(jTextFieldTENKH.getText().toString(), jTableKhachhang.getSelectedRow(), 1);
			model.setValueAt(jTextFieldCMND.getText(), jTableKhachhang.getSelectedRow(), 2);
			model.setValueAt(jTextFieldQUOCTICH.getText(), jTableKhachhang.getSelectedRow(), 3);
			model.setValueAt(comboBoxGIOITINH.getSelectedItem(), jTableKhachhang.getSelectedRow(), 4);
			model.setValueAt(jTextFieldTUOI.getText(), jTableKhachhang.getSelectedRow(), 5);
			model.setValueAt(jTextFieldSDT.getText(), jTableKhachhang.getSelectedRow(), 6);
			model.setValueAt(comboBoxMAPHONGKH.getSelectedItem(), jTableKhachhang.getSelectedRow(), 7);
			Connection con = getConnection();
			try {
				st = (Statement) con.createStatement();
				String query = String.format(
						"UPDATE KhachHang SET TENKH ='%s', CMND = %s , QUOCTICH ='%s' ,GIOITINH ='%s' , TUOI = %s , SDT = %s ,  MAPHONG = '%s' WHERE MAKH = '%s'",
						jTextFieldTENKH.getText(), jTextFieldCMND.getText(), jTextFieldQUOCTICH.getText(),
						comboBoxGIOITINH.getSelectedItem(), jTextFieldTUOI.getText(), jTextFieldSDT.getText(), maPhong,
						jTextFieldMAKH.getText());

				System.out.println("sql : " + query);

				st.execute(query);
				hienThiDanhSachKhachHang();

			} catch (Exception ex) {
				ex.printStackTrace();
			}

		}

	}// GEN-LAST:event_sua1ActionPerformed

	private void xoa1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_xoa1ActionPerformed
		// TODO add your handling code here:
		Connection con = getConnection();
		try {
			// Táº¡o má»™t Ä‘á»‘i tÆ°á»£ng Ä‘á»ƒ thá»±c hiá»‡n cÃ´ng viá»‡c
			st = (Statement) con.createStatement();
			String query = "DELETE FROM khachhang WHERE MAKH = '" + jTextFieldMAKH.getText() + "'";
			st.executeUpdate(query);
			hienThiDanhSachKhachHang();

		} catch (Exception ex) {

			ex.printStackTrace();
		}
	}// GEN-LAST:event_xoa1ActionPerformed

	private void thoat1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_thoat1ActionPerformed
		// TODO add your handling code here:
		thoat1.setToolTipText("Click Ảnh để thoát chương trình");
		int selected = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thoát chương trình" + " trên không",
				"thông báo", JOptionPane.YES_NO_CANCEL_OPTION);
		if (selected == JOptionPane.YES_NO_OPTION) {
			this.dispose();

		}
	}// GEN-LAST:event_thoat1ActionPerformed

	private void jButtonclear2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonclear2ActionPerformed

		setEmptyAll();
		jTextFieldMAKH.requestFocus();

	}// GEN-LAST:event_jButtonclear2ActionPerformed

	private void jTableKhachhangMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTableKhachhangMouseClicked
		// TODO add your handling code here:
		int i = jTableKhachhang.getSelectedRow();
		TableModel model = jTableKhachhang.getModel();
		jTextFieldMAKH.setText(model.getValueAt(i, 0).toString());
		jTextFieldTENKH.setText(model.getValueAt(i, 1).toString());
		jTextFieldCMND.setText(model.getValueAt(i, 2).toString());
		jTextFieldQUOCTICH.setText(model.getValueAt(i, 3).toString());
		comboBoxGIOITINH.setSelectedIndex(model.getValueAt(i, 4).toString().equals("NAM") ? 0 : 1);
		jTextFieldTUOI.setText(model.getValueAt(i, 5).toString());
		jTextFieldSDT.setText(model.getValueAt(i, 6).toString());

		String maPhong = model.getValueAt(i, 7).toString();
		int index = 0;
		for (Phong phong : dsphong) {
			if (phong.getMaPhong().equals(maPhong)) {
				break;
			}
			index++;
		}		
		comboBoxMAPHONGKH.setSelectedIndex(index);
	}// GEN-LAST:event_jTableKhachhangMouseClicked

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(khachhangform.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(khachhangform.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(khachhangform.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(khachhangform.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new khachhangform().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private JButton jButtonclear2;
	private JLabel jLabel10;
	private JLabel jLabel11;
	private JLabel jLabel12;
	private JLabel jLabel13;
	private JLabel jLabel14;
	private JLabel jLabel15;
	private JLabel jLabel16;
	private JLabel jLabel17;
	private JLabel jLabel9;
	private JPanel jPanel11;
	private JPanel jPanel12;
	private JScrollPane jScrollPane2;
	private JTable jTableKhachhang;
	private JTextField jTextFieldCMND;
	private JTextField jTextFieldMAKH;
	private JTextField jTextFieldQUOCTICH;
	private JTextField jTextFieldSDT;
	private JTextField jTextFieldTENKH;
	private JTextField jTextFieldTUOI;
	private JButton sua1;
	private JButton them1;
	private JButton thoat1;
	private JButton xoa1;
	private JPanel jPanel4;
	@SuppressWarnings("rawtypes")
	private JComboBox comboBoxGIOITINH;
	@SuppressWarnings("rawtypes")
	private JComboBox comboBoxMAPHONGKH;

	// End of variables declaration//GEN-END:variables

	private void setLocationDefault(int w, int h) {
		Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

		int x = (dim.width - w) / 2;
		int y = (dim.height - h) / 2;

		// Move the window
		this.setLocation(x, y);
	}

	private void setEmptyAll() {
		jTextFieldMAKH.setText("");
		jTextFieldTENKH.setText("");
		jTextFieldCMND.setText("");
		jTextFieldQUOCTICH.setText("");
		comboBoxGIOITINH.setSelectedIndex(0);
		jTextFieldTUOI.setText("");
		jTextFieldSDT.setText("");
		comboBoxMAPHONGKH.setSelectedIndex(0);
	}

	@SuppressWarnings("unchecked")
	private void loadComboxbo() {
		dsphong = phongControl.layDanhSachEmpty();

		DefaultComboBoxModel<Phong> comboBoxModelPhong = new DefaultComboBoxModel<>(
				dsphong.toArray(new Phong[dsphong.size()]));
		comboBoxMAPHONGKH.setModel(comboBoxModelPhong);

	}

}
