/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlksk57.Form;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import org.apache.commons.lang3.StringUtils;

import qlksk57.control.NhanVienControl;
import qlksk57.models.NhanVien;

import static qlksk57.MyConnection.getConnection;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JComboBox;
import javax.swing.SwingConstants;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author khoa
 */
public class nhanvienform extends javax.swing.JFrame {

	NhanVienControl nhanVienControl = new NhanVienControl();

	/**
	 * Creates new form nhanvienform
	 */
	public nhanvienform() {
		setResizable(false);
		initComponents();
		getConnection();
		hienThiDanhSachNhanVien();
		
		setLocationDefault(1110, 700);
	}

	Connection con = null;
	Statement st = null;

	public void hienThiDanhSachNhanVien() {
		String colTieuDe1[] = new String[] { "Mã nhân viên", "Tên nhân viên", "Chức vụ", "Lương", "Ngày Sinh",
				"Giới tính", "Chú thích" };
		ArrayList<NhanVien> dsnv = nhanVienControl.layDanhSachNhanVien();

		DefaultTableModel model = new DefaultTableModel(colTieuDe1, 0);

		Object[] row;

		for (int i = 0; i < dsnv.size(); i++) {

			row = new Object[7];

			// GÃ�N GIÃ� TRá»Š
			row[0] = dsnv.get(i).getMaNV();
			row[1] = dsnv.get(i).getTenNV();
			row[2] = dsnv.get(i).getChucVu();
			row[3] = dsnv.get(i).getLuongNV();
			row[4] = dsnv.get(i).getNgaySinh();
			row[5] = dsnv.get(i).getGioiTinh();
			row[6] = dsnv.get(i).getChuThich();

			model.addRow(row);
		}

		// }catch(ArrayIndexOutOfBoundsException ex){

		jTableNhanvien.setModel(model);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel3 = new javax.swing.JPanel();
		jPanel8 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jPanel9 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jTextFieldMANV = new javax.swing.JTextField();
		jTextFieldTENNV = new javax.swing.JTextField();
		jTextFieldCHUCVU = new javax.swing.JTextField();
		jTextFieldLUONG = new javax.swing.JTextField();
		jTextFieldNGAYSINH = new javax.swing.JTextField();
		jTextFieldCHUTHICH = new javax.swing.JTextField();
		them = new javax.swing.JButton();
		sua = new javax.swing.JButton();
		xoa = new javax.swing.JButton();
		thoat = new javax.swing.JButton();
		jButtonclear = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTableNhanvien = new javax.swing.JTable();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel3.setBackground(new java.awt.Color(51, 204, 255));

		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		jLabel1.setText("QUẢN LÍ NHÂN VIÊN");

		javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
		jPanel8Layout.setHorizontalGroup(jPanel8Layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(Alignment.LEADING, jPanel8Layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabel1).addContainerGap(16, Short.MAX_VALUE)));
		jPanel8Layout.setVerticalGroup(jPanel8Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel8Layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 44, GroupLayout.PREFERRED_SIZE)
						.addContainerGap(38, Short.MAX_VALUE)));
		jPanel8.setLayout(jPanel8Layout);

		jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông Tin Nhân Viên"));

		jLabel2.setText("Mã nhân viên ");

		jLabel3.setText("Tên nhân viên");

		jLabel4.setText("Chức vụ");

		jLabel5.setText("Lương");

		jLabel6.setText("Ngày  Sinh");

		jLabel7.setText("Giới tính");

		jLabel8.setText("Chú thích");

		jTextFieldTENNV.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldTENNVActionPerformed(evt);
			}
		});

		jTextFieldLUONG.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldLUONGActionPerformed(evt);
			}
		});

		them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlksk57/Form/hinh/THEM.png"))); // NOI18N
		them.setText("Thêm");
		them.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				themActionPerformed(evt);
			}
		});

		sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlksk57/Form/hinh/SUA.png"))); // NOI18N
		sua.setText("Sửa");
		sua.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				suaActionPerformed(evt);
			}
		});

		xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlksk57/Form/hinh/XOA.png"))); // NOI18N
		xoa.setText("Xóa");
		xoa.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				xoaActionPerformed(evt);
			}
		});

		thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlksk57/Form/hinh/THOAT.png"))); // NOI18N
		thoat.setText("Thoát");
		thoat.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				thoatActionPerformed(evt);
			}
		});

		jButtonclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlksk57/Form/hinh/CLEAR.png"))); // NOI18N
		jButtonclear.setText("Clear");
		jButtonclear.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonclearActionPerformed(evt);
			}
		});
		String gender[] = { "NAM", "NỮ" };

		comboBoxGIOITINH = new JComboBox(gender);

		javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
		jPanel9Layout.setHorizontalGroup(jPanel9Layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(jPanel9Layout.createSequentialGroup()
						.addGroup(jPanel9Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel9Layout.createSequentialGroup().addContainerGap()
										.addGroup(jPanel9Layout.createParallelGroup(Alignment.LEADING, false)
												.addComponent(xoa, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(them, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE))
										.addGap(18)
										.addGroup(jPanel9Layout.createParallelGroup(Alignment.LEADING, false)
												.addComponent(sua, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(thoat, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE))
										.addGap(18)
										.addComponent(
												jButtonclear, GroupLayout.PREFERRED_SIZE, 87,
												GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(ComponentPlacement.RELATED, 58, Short.MAX_VALUE))
								.addGroup(jPanel9Layout.createSequentialGroup().addGap(19).addGroup(jPanel9Layout
										.createParallelGroup(Alignment.LEADING)
										.addGroup(jPanel9Layout.createSequentialGroup()
												.addGroup(jPanel9Layout.createParallelGroup(Alignment.LEADING)
														.addComponent(jLabel2).addComponent(jLabel5)
														.addComponent(jLabel3).addComponent(jLabel4))
												.addPreferredGap(ComponentPlacement.RELATED)
												.addGroup(jPanel9Layout.createParallelGroup(Alignment.TRAILING, false)
														.addComponent(jTextFieldTENNV, GroupLayout.DEFAULT_SIZE, 226,
																Short.MAX_VALUE)
														.addComponent(jTextFieldMANV)
														.addComponent(
																jTextFieldCHUCVU, Alignment.LEADING)
														.addComponent(jTextFieldLUONG)))
										.addGroup(jPanel9Layout.createSequentialGroup().addGroup(jPanel9Layout
												.createParallelGroup(Alignment.LEADING)
												.addGroup(jPanel9Layout.createParallelGroup(Alignment.TRAILING, false)
														.addComponent(jLabel7, GroupLayout.DEFAULT_SIZE,
																GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(jLabel6, GroupLayout.DEFAULT_SIZE,
																GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
												.addComponent(jLabel8)).addPreferredGap(ComponentPlacement.RELATED)
												.addGroup(jPanel9Layout.createParallelGroup(Alignment.LEADING)
														.addComponent(jTextFieldNGAYSINH, Alignment.TRAILING,
																GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
														.addComponent(comboBoxGIOITINH, 0, 226, Short.MAX_VALUE)
														.addComponent(jTextFieldCHUTHICH, GroupLayout.DEFAULT_SIZE, 226,
																Short.MAX_VALUE))
												.addGap(35)))))
						.addContainerGap()));
		jPanel9Layout.setVerticalGroup(jPanel9Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel9Layout
				.createSequentialGroup().addGap(19)
				.addGroup(jPanel9Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jTextFieldMANV, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel2))
				.addPreferredGap(ComponentPlacement.UNRELATED)
				.addGroup(jPanel9Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jTextFieldTENNV, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel3))
				.addPreferredGap(ComponentPlacement.UNRELATED)
				.addGroup(jPanel9Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jTextFieldCHUCVU, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel4))
				.addPreferredGap(ComponentPlacement.UNRELATED)
				.addGroup(jPanel9Layout
						.createParallelGroup(Alignment.BASELINE).addComponent(jLabel5).addComponent(jTextFieldLUONG,
								GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(ComponentPlacement.UNRELATED)
				.addGroup(jPanel9Layout
						.createParallelGroup(Alignment.BASELINE).addComponent(jLabel6).addComponent(jTextFieldNGAYSINH,
								GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(ComponentPlacement.UNRELATED)
				.addGroup(jPanel9Layout
						.createParallelGroup(Alignment.BASELINE).addComponent(jLabel7).addComponent(comboBoxGIOITINH,
								GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(ComponentPlacement.RELATED)
				.addGroup(jPanel9Layout
						.createParallelGroup(Alignment.BASELINE).addComponent(jLabel8).addComponent(jTextFieldCHUTHICH,
								GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
				.addGap(18)
				.addGroup(jPanel9Layout.createParallelGroup(Alignment.BASELINE).addComponent(them).addComponent(sua)
						.addComponent(jButtonclear))
				.addGap(18)
				.addGroup(jPanel9Layout.createParallelGroup(Alignment.BASELINE).addComponent(xoa).addComponent(thoat))
				.addContainerGap(29, Short.MAX_VALUE)));
		jPanel9Layout.linkSize(SwingConstants.VERTICAL,
				new Component[] { jLabel2, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jTextFieldMANV, jTextFieldTENNV,
						jTextFieldCHUCVU, jTextFieldLUONG, jTextFieldNGAYSINH, jTextFieldCHUTHICH, xoa,
						comboBoxGIOITINH });
		jPanel9Layout.linkSize(SwingConstants.HORIZONTAL,
				new Component[] { jLabel2, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8 });
		jPanel9.setLayout(jPanel9Layout);

		jTableNhanvien
				.setModel(new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jTableNhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jTableNhanvienMouseClicked(evt);
			}
		});
		jScrollPane1.setViewportView(jTableNhanvien);

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3Layout.setHorizontalGroup(
			jPanel3Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup()
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel3Layout.createSequentialGroup()
							.addContainerGap()
							.addComponent(jPanel9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
							.addGap(26)
							.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 652, GroupLayout.PREFERRED_SIZE))
						.addGroup(jPanel3Layout.createSequentialGroup()
							.addGap(406)
							.addComponent(jPanel8, GroupLayout.PREFERRED_SIZE, 248, GroupLayout.PREFERRED_SIZE)))
					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);
		jPanel3Layout.setVerticalGroup(
			jPanel3Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup()
					.addContainerGap()
					.addComponent(jPanel8, GroupLayout.PREFERRED_SIZE, 63, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(jPanel3Layout.createParallelGroup(Alignment.TRAILING, false)
						.addComponent(jPanel9, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addContainerGap())
		);
		jPanel3.setLayout(jPanel3Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING).addComponent(jPanel3,
				GroupLayout.DEFAULT_SIZE, 1005, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING).addComponent(jPanel3,
				GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE));
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jTableNhanvienMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTableNhanvienMouseClicked

		// TODO add your handling code here:
		int i = jTableNhanvien.getSelectedRow();
		TableModel model = jTableNhanvien.getModel();
		jTextFieldMANV.setText(model.getValueAt(i, 0).toString());
		jTextFieldTENNV.setText(model.getValueAt(i, 1).toString());
		jTextFieldCHUCVU.setText(model.getValueAt(i, 2).toString());
		jTextFieldLUONG.setText(model.getValueAt(i, 3).toString());
		jTextFieldNGAYSINH.setText(model.getValueAt(i, 4).toString());
		comboBoxGIOITINH.setSelectedIndex(model.getValueAt(i, 5).toString().equals("NAM") ? 0 : 1);
		jTextFieldCHUTHICH.setText(model.getValueAt(i, 6).toString());
	}// GEN-LAST:event_jTableNhanvienMouseClicked

	private void jButtonclearActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonclearActionPerformed
		setEmptyAll();
		jTextFieldMANV.requestFocus();
	}// GEN-LAST:event_jButtonclearActionPerformed

	private void thoatActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_thoatActionPerformed
		// TODO add your handling code here:
		thoat.setToolTipText("Click Ảnh để thoát chương trình ");
		int selected = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thoát chương trình" + " trên không",
				"Thông báo", JOptionPane.YES_NO_CANCEL_OPTION);
		if (selected == JOptionPane.YES_NO_OPTION) {
			this.dispose();

		}
	}// GEN-LAST:event_thoatActionPerformed

	private void xoaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_xoaActionPerformed

		if (StringUtils.isEmpty(jTextFieldMANV.getText())) {
			JOptionPane.showMessageDialog(this, "Vui lòng kiểm tra Mã");
			return;
		}

		
		Connection con = getConnection();
		try {
			// Táº¡o má»™t Ä‘á»‘i tÆ°á»£ng Ä‘á»ƒ thá»±c hiá»‡n cÃ´ng viá»‡c
			st = (Statement) con.createStatement();
			String query = "DELETE FROM NhanVien WHERE MANV = '" + jTextFieldMANV.getText() + "'";
			st.executeUpdate(query);
			hienThiDanhSachNhanVien();
			setEmptyAll();
		} catch (Exception ex) {

			System.out.println(ex.getMessage());
			JOptionPane.showMessageDialog(this, ex.getMessage());
			// ex.printStackTrace();
		}
	}// GEN-LAST:event_xoaActionPerformed

	private void suaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_suaActionPerformed
		// TODO add your handling code here:

		if (jTableNhanvien.getSelectedRow() == -1) {
			if (jTableNhanvien.getRowCount() == 0) {
				// lblError.setText("Table is empty");
			} else {
				// lblError.setText("You must select a Tennis Player");
			}
		} else {

			if (StringUtils.isEmpty(jTextFieldMANV.getText()) || StringUtils.isEmpty(jTextFieldTENNV.getText())
					|| StringUtils.isEmpty(jTextFieldLUONG.getText())) {
				JOptionPane.showMessageDialog(this, "Vui lòng kiểm tra Mã ,Tên, Chức vụ");
				return;
			}

			DefaultTableModel model = (DefaultTableModel) jTableNhanvien.getModel();
			model.setValueAt(jTextFieldMANV.getText(), jTableNhanvien.getSelectedRow(), 0);
			model.setValueAt(jTextFieldTENNV.getText().toString(), jTableNhanvien.getSelectedRow(), 1);
			model.setValueAt(jTextFieldCHUCVU.getText(), jTableNhanvien.getSelectedRow(), 2);
			model.setValueAt(jTextFieldLUONG.getText(), jTableNhanvien.getSelectedRow(), 2);
			model.setValueAt(jTextFieldNGAYSINH.getText(), jTableNhanvien.getSelectedRow(), 2);
			model.setValueAt(comboBoxGIOITINH.getSelectedItem(), jTableNhanvien.getSelectedRow(), 2);
			model.setValueAt(jTextFieldCHUTHICH.getText(), jTableNhanvien.getSelectedRow(), 2);

			Connection con = getConnection();
			try {
				st = (Statement) con.createStatement();
				String query = String.format(
						"UPDATE NhanVien SET TENNV ='%s', CHUCVU = '%s' , LUONGNV = %s ,NGAYSINH = '%s' , GIOITINH ='%s' , CHUTHICH = '%s' WHERE MANV = '%s'",
						jTextFieldTENNV.getText(), jTextFieldCHUCVU.getText(), jTextFieldLUONG.getText(),
						jTextFieldNGAYSINH.getText(), comboBoxGIOITINH.getSelectedItem(), jTextFieldCHUTHICH.getText(),
						jTextFieldMANV.getText());

				System.out.println("sql : " + query);
				st.execute(query);
				hienThiDanhSachNhanVien();
				setEmptyAll();
				
			} catch (Exception ex) {

				System.out.println(ex.getMessage());
				JOptionPane.showMessageDialog(this, ex.getMessage());
				// ex.printStackTrace();
			}
		}
	}// GEN-LAST:event_suaActionPerformed

	private void themActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_themActionPerformed

		if (StringUtils.isEmpty(jTextFieldMANV.getText()) || StringUtils.isEmpty(jTextFieldTENNV.getText())
				|| StringUtils.isEmpty(jTextFieldLUONG.getText())) {
			JOptionPane.showMessageDialog(this, "Vui lòng kiểm tra Mã ,Tên, Chức vụ");
			return;
		}

		Connection con = getConnection();
		try {
			st = (Statement) con.createStatement();
			String query = "INSERT INTO NhanVien(MANV,TENNV,CHUCVU, LUONGNV, NGAYSINH, GIOITINH, CHUTHICH) VALUES('"
					+ jTextFieldMANV.getText() + "'," + "'" + jTextFieldTENNV.getText() + "','"
					+ jTextFieldCHUCVU.getText() + "','" + jTextFieldLUONG.getText() + "','"
					+ jTextFieldNGAYSINH.getText() + "','" + comboBoxGIOITINH.getSelectedItem() + "','"
					+ jTextFieldCHUTHICH.getText() + "')";

			st.execute(query);
			hienThiDanhSachNhanVien();
			setEmptyAll();
			
		} catch (Exception ex) {

			System.out.println(ex.getMessage());
			JOptionPane.showMessageDialog(this, ex.getMessage());
			// ex.printStackTrace();
		}
	}// GEN-LAST:event_themActionPerformed

	private void jTextFieldLUONGActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldLUONGActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextFieldLUONGActionPerformed

	private void jTextFieldTENNVActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldTENNVActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextFieldTENNVActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(nhanvienform.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(nhanvienform.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(nhanvienform.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(nhanvienform.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new nhanvienform().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButtonclear;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel8;
	private javax.swing.JPanel jPanel9;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTableNhanvien;
	private javax.swing.JTextField jTextFieldCHUCVU;
	private javax.swing.JTextField jTextFieldCHUTHICH;
	private javax.swing.JTextField jTextFieldLUONG;
	private javax.swing.JTextField jTextFieldMANV;
	private javax.swing.JTextField jTextFieldNGAYSINH;
	private javax.swing.JTextField jTextFieldTENNV;
	private javax.swing.JButton sua;
	private javax.swing.JButton them;
	private javax.swing.JButton thoat;
	private javax.swing.JButton xoa;
	private JComboBox comboBoxGIOITINH;
	// End of variables declaration//GEN-END:variables

	private void setEmptyAll() {
		jTextFieldMANV.setText("");
		jTextFieldTENNV.setText("");
		jTextFieldCHUCVU.setText("");
		jTextFieldLUONG.setText("");
		jTextFieldNGAYSINH.setText("");
		comboBoxGIOITINH.setSelectedIndex(0);
		jTextFieldCHUTHICH.setText("");
	}


	private void setLocationDefault(int w, int h) {
		Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

		int x = (dim.width - w) / 2;
		int y = (dim.height - h) / 2;

		// Move the window
		this.setLocation(x, y);
	}

	
}
