/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlksk57.Form;

import static qlksk57.MyConnection.getConnection;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.Statement;
import java.util.ArrayList;

import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import org.apache.commons.lang3.StringUtils;

import qlksk57.control.DichVuControl;
import qlksk57.control.NhanVienControl;
import qlksk57.control.PhongControl;
import qlksk57.models.DichVu;
import qlksk57.models.NhanVien;
import qlksk57.models.Phong;

public class phongform extends javax.swing.JFrame {

	DichVuControl dichVuControl = new DichVuControl();
	NhanVienControl nhanVienControl = new NhanVienControl();
	PhongControl phongControl = new PhongControl();
	

	ArrayList<DichVu> dsdv = null;
	ArrayList<NhanVien> dsnv = null;


	public phongform() {
		setResizable(false);
		initComponents();

		getConnection();
		loadComboxbo();
		hienThiDanhSachPhong();
		setLocationDefault(1100, 700);
	}

	Connection con = null;
	Statement st = null;

	public void hienThiDanhSachPhong() {
		String colTieuDe1[] = new String[] { "Mã Phòng", "Tên Phòng", "Loại Phòng", "Gía Phòng", "Chú Thích",
				"Tình Trạng", "Mã Nhân Viên", "Mã Dịch Vụ" };
		ArrayList<Phong> dsp = phongControl.layDanhSachPhong();

		DefaultTableModel model = new DefaultTableModel(colTieuDe1, 0);

		Object[] row;

		for (int i = 0; i < dsp.size(); i++) {

			row = new Object[8];

			// GÃ�N GIÃ� TRá»Š
			row[0] = dsp.get(i).getMaPhong();
			row[1] = dsp.get(i).getTenPhong();
			row[2] = dsp.get(i).getLoaiPhong();
			row[3] = dsp.get(i).getGiaPhong();
			row[4] = dsp.get(i).getChuThich();
			row[5] = dsp.get(i).getTinhTrang();
			row[6] = dsp.get(i).getMaNV();
			row[7] = dsp.get(i).getMaDV();

			model.addRow(row);
		}

		// }catch(ArrayIndexOutOfBoundsException ex){

		jTablePHONG.setModel(model);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel5 = new javax.swing.JPanel();
		jPanel17 = new javax.swing.JPanel();
		jLabel22 = new javax.swing.JLabel();
		jScrollPane4 = new javax.swing.JScrollPane();
		jTablePHONG = new javax.swing.JTable();
		jPanel18 = new javax.swing.JPanel();
		jLabel23 = new javax.swing.JLabel();
		jLabel24 = new javax.swing.JLabel();
		jLabel25 = new javax.swing.JLabel();
		jLabel26 = new javax.swing.JLabel();
		jLabel27 = new javax.swing.JLabel();
		jLabel28 = new javax.swing.JLabel();
		jTextFieldMAPHONG = new javax.swing.JTextField();
		jTextFieldTENPHONG = new javax.swing.JTextField();
		jTextFieldGIAPHONG = new javax.swing.JTextField();
		jTextFieldCHUTHICHP = new javax.swing.JTextField();
		jTextFieldTINHTRANG = new javax.swing.JTextField();
		them3 = new javax.swing.JButton();
		sua3 = new javax.swing.JButton();
		xoa3 = new javax.swing.JButton();
		thoat3 = new javax.swing.JButton();
		jLabel29 = new javax.swing.JLabel();
		jLabel30 = new javax.swing.JLabel();
		jButtonclear3 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel5.setBackground(new java.awt.Color(51, 204, 255));

		jLabel22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
		jLabel22.setText("QUẢN LÍ PHÒNG");

		javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
		jPanel17Layout.setHorizontalGroup(jPanel17Layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(Alignment.LEADING, jPanel17Layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabel22).addContainerGap(155, Short.MAX_VALUE)));
		jPanel17Layout.setVerticalGroup(jPanel17Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel17Layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabel22, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGap(42)));
		jPanel17.setLayout(jPanel17Layout);

		jTablePHONG
				.setModel(new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jTablePHONG.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jTablePHONGMouseClicked(evt);
			}
		});
		jScrollPane4.setViewportView(jTablePHONG);

		jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông Tin Phòng"));

		jLabel23.setText("Mã Phòng");

		jLabel24.setText("Tên Phòng");

		jLabel25.setText("Loại Phòng");

		jLabel26.setText("Gía Phòng");

		jLabel27.setText("Chú Thích");

		jLabel28.setText("Tình Trạng");

		them3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlksk57/Form/hinh/THEM.png"))); // NOI18N
		them3.setText("Thêm");
		them3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				them3ActionPerformed(evt);
			}
		});

		sua3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlksk57/Form/hinh/SUA.png"))); // NOI18N
		sua3.setText("Sửa");
		sua3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				sua3ActionPerformed(evt);
			}
		});

		xoa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlksk57/Form/hinh/XOA.png"))); // NOI18N
		xoa3.setText("Xóa");
		xoa3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				xoa3ActionPerformed(evt);
			}
		});

		thoat3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlksk57/Form/hinh/THOAT.png"))); // NOI18N
		thoat3.setText("Thoát");
		thoat3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				thoat3ActionPerformed(evt);
			}
		});

		jLabel29.setText("Mã Nhân Viên");

		jLabel30.setText("Mã Dịch Vụ");

		jButtonclear3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlksk57/Form/hinh/CLEAR.png"))); // NOI18N
		jButtonclear3.setText("Clear");
		jButtonclear3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonclear3ActionPerformed(evt);
			}
		});

		String loaiPhong[] = { "VIP", "THƯỜNG" };
		comboBoxLOAIPHONG = new JComboBox(loaiPhong);

		comboBoxMANVP = new JComboBox();

		comboBoxMADVP = new JComboBox();

		javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
		jPanel18Layout.setHorizontalGroup(jPanel18Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel18Layout
				.createSequentialGroup().addGap(21)
				.addGroup(jPanel18Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel18Layout.createSequentialGroup()
								.addGroup(jPanel18Layout
										.createParallelGroup(Alignment.LEADING).addComponent(xoa3).addComponent(them3))
								.addGap(6, 6, Short.MAX_VALUE)
								.addGroup(jPanel18Layout.createParallelGroup(Alignment.TRAILING, false)
										.addComponent(sua3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(thoat3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE))
								.addGap(18).addComponent(jButtonclear3))
						.addGroup(jPanel18Layout.createSequentialGroup()
								.addGroup(jPanel18Layout.createParallelGroup(Alignment.LEADING).addComponent(jLabel23)
										.addComponent(jLabel24).addComponent(jLabel25).addComponent(jLabel26)
										.addComponent(jLabel27).addComponent(jLabel28).addComponent(jLabel29)
										.addComponent(jLabel30))
								.addGap(34)
								.addGroup(jPanel18Layout.createParallelGroup(Alignment.LEADING, false)
										.addComponent(comboBoxMANVP, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(comboBoxLOAIPHONG, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jTextFieldTENPHONG).addComponent(jTextFieldGIAPHONG)
										.addComponent(jTextFieldCHUTHICHP).addComponent(jTextFieldTINHTRANG)
										.addComponent(jTextFieldMAPHONG, GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
										.addComponent(comboBoxMADVP, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addPreferredGap(ComponentPlacement.RELATED, 17, Short.MAX_VALUE)))
				.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel18Layout.setVerticalGroup(jPanel18Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel18Layout.createSequentialGroup().addGap(22)
						.addGroup(jPanel18Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel18Layout.createSequentialGroup()
										.addComponent(jTextFieldMAPHONG, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(ComponentPlacement.RELATED)
										.addComponent(jTextFieldTENPHONG, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(ComponentPlacement.RELATED)
										.addComponent(comboBoxLOAIPHONG, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(ComponentPlacement.RELATED)
										.addComponent(jTextFieldGIAPHONG, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(ComponentPlacement.RELATED)
										.addComponent(jTextFieldCHUTHICHP, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(ComponentPlacement.RELATED)
										.addComponent(jTextFieldTINHTRANG, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(ComponentPlacement.RELATED)
										.addComponent(comboBoxMANVP, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(ComponentPlacement.RELATED).addComponent(comboBoxMADVP,
												GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel18Layout.createSequentialGroup().addComponent(jLabel23)
										.addPreferredGap(ComponentPlacement.RELATED).addComponent(jLabel24)
										.addPreferredGap(ComponentPlacement.RELATED).addComponent(jLabel25)
										.addPreferredGap(ComponentPlacement.RELATED).addComponent(jLabel26)
										.addPreferredGap(ComponentPlacement.RELATED).addComponent(jLabel27)
										.addPreferredGap(ComponentPlacement.RELATED).addComponent(jLabel28)
										.addPreferredGap(ComponentPlacement.RELATED).addComponent(jLabel29)
										.addPreferredGap(ComponentPlacement.RELATED).addComponent(jLabel30)))
						.addGap(31)
						.addGroup(jPanel18Layout.createParallelGroup(Alignment.BASELINE).addComponent(them3)
								.addComponent(sua3).addComponent(jButtonclear3))
						.addGap(18).addGroup(jPanel18Layout.createParallelGroup(Alignment.BASELINE).addComponent(xoa3)
								.addComponent(thoat3))
						.addContainerGap(52, Short.MAX_VALUE)));
		jPanel18Layout.linkSize(SwingConstants.VERTICAL,
				new Component[] { jLabel23, jLabel24, jLabel25, jLabel26, jLabel27, jLabel28, jTextFieldMAPHONG,
						jTextFieldTENPHONG, jTextFieldGIAPHONG, jTextFieldCHUTHICHP, jTextFieldTINHTRANG, jLabel29,
						jLabel30, comboBoxLOAIPHONG, comboBoxMANVP, comboBoxMADVP });
		jPanel18.setLayout(jPanel18Layout);

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
		jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel5Layout.createSequentialGroup()
						.addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel5Layout.createSequentialGroup().addContainerGap()
										.addComponent(jPanel18, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(ComponentPlacement.RELATED)
										.addComponent(jScrollPane4, GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE))
								.addGroup(jPanel5Layout.createSequentialGroup().addGap(438).addComponent(jPanel17,
										GroupLayout.PREFERRED_SIZE, 199, GroupLayout.PREFERRED_SIZE)))
						.addContainerGap()));
		jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel5Layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel17, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE).addGap(18)
						.addGroup(jPanel5Layout.createParallelGroup(Alignment.LEADING, false)
								.addComponent(jPanel18, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE,
										GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jScrollPane4, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 414,
										Short.MAX_VALUE))
						.addContainerGap(19, Short.MAX_VALUE)));
		jPanel5.setLayout(jPanel5Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING).addComponent(jPanel5,
				Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 1094, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING).addComponent(jPanel5,
				GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE));
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jTablePHONGMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTablePHONGMouseClicked
		// TODO add your handling code here:
		int i = jTablePHONG.getSelectedRow();
		TableModel model = jTablePHONG.getModel();
		jTextFieldMAPHONG.setText(model.getValueAt(i, 0).toString());
		jTextFieldTENPHONG.setText(model.getValueAt(i, 1).toString());
		comboBoxLOAIPHONG.setSelectedIndex(model.getValueAt(i, 2).toString().equals("VIP") ? 0 : 1);
		jTextFieldGIAPHONG.setText(model.getValueAt(i, 3).toString());
		String chuThich = model.getValueAt(i, 4) == null ? "" : model.getValueAt(i, 4).toString() ;
		jTextFieldCHUTHICHP.setText(chuThich);
		String tinhTrang = model.getValueAt(i, 5) == null ? "" : model.getValueAt(i, 5).toString() ;
		jTextFieldTINHTRANG.setText(tinhTrang);

		String maNV = model.getValueAt(i, 6).toString();
		String maDV = model.getValueAt(i, 7).toString();

		int index = 0;
		for (NhanVien nv : dsnv) {
			if (nv.getMaNV().equals(maNV)) {
				break;
			}
			index++;
		}		
		comboBoxMANVP.setSelectedIndex(index);
		
		index = 0;
		for (DichVu dv : dsdv) {
			if (dv.getMaDV().equals(maDV)) {
				break;
			}
			index++;
		}		
		comboBoxMADVP.setSelectedIndex(index);
		
		
	}// GEN-LAST:event_jTablePHONGMouseClicked

	private void them3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_them3ActionPerformed

		if (StringUtils.isEmpty(jTextFieldMAPHONG.getText()) || StringUtils.isEmpty(jTextFieldTENPHONG.getText())
				|| StringUtils.isEmpty(jTextFieldGIAPHONG.getText())) {
			JOptionPane.showMessageDialog(this, "Vui lòng kiểm tra Mã phòng, Tên phòng, Giá phòng");
			return;
		}

		Connection con = getConnection();
		try {
			String maNV = ((NhanVien)comboBoxMANVP.getSelectedObjects()[0]).getMaNV();
			String maDV = ((DichVu)comboBoxMADVP.getSelectedObjects()[0]).getMaDV();
			
			st = (Statement) con.createStatement();
			String query = "INSERT INTO phong(MAPHONG,TENPHONG, LOAIPHONG, GIAPHONG, CHUTHICH, TINHTRANG, MANV, MADV) VALUES('"
					+ jTextFieldMAPHONG.getText() + "'," + "'" + jTextFieldTENPHONG.getText() + "','"
					+ comboBoxLOAIPHONG.getSelectedItem() + "', '" + jTextFieldGIAPHONG.getText() + "', '"
					+ jTextFieldCHUTHICHP.getText() + "', '" + jTextFieldTINHTRANG.getText() + "', '"
					+ maNV + "', '" + maDV + "')";

			st.execute(query);
			hienThiDanhSachPhong();
			
			setEmptyAll();

		} catch (Exception ex) {
			System.out.println(ex.getMessage());
			JOptionPane.showMessageDialog(this, ex.getMessage());
			// ex.printStackTrace();
		}

	}// GEN-LAST:event_them3ActionPerformed

	private void sua3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_sua3ActionPerformed
		if (jTablePHONG.getSelectedRow() == -1) {
			if (jTablePHONG.getRowCount() == 0) {
				// lblError.setText("Table is empty");
			} else {
				// lblError.setText("You must select a Tennis Player");
			}
		} else {

			if (StringUtils.isEmpty(jTextFieldMAPHONG.getText()) || StringUtils.isEmpty(jTextFieldTENPHONG.getText())
					|| StringUtils.isEmpty(jTextFieldGIAPHONG.getText())) {
				JOptionPane.showMessageDialog(this, "Vui lòng kiểm tra Mã phòng, tên phòng, giá phòng");
				return;
			}
			
			String maNV = ((NhanVien)comboBoxMANVP.getSelectedObjects()[0]).getMaNV();
			String maDV = ((DichVu)comboBoxMADVP.getSelectedObjects()[0]).getMaDV();
			

			DefaultTableModel model = (DefaultTableModel) jTablePHONG.getModel();
			model.setValueAt(jTextFieldMAPHONG.getText(), jTablePHONG.getSelectedRow(), 0);
			model.setValueAt(jTextFieldTENPHONG.getText().toString(), jTablePHONG.getSelectedRow(), 1);
			model.setValueAt(comboBoxLOAIPHONG.getSelectedItem(), jTablePHONG.getSelectedRow(), 2);
			model.setValueAt(jTextFieldGIAPHONG.getText(), jTablePHONG.getSelectedRow(), 3);
			model.setValueAt(jTextFieldCHUTHICHP.getText(), jTablePHONG.getSelectedRow(), 4);
			model.setValueAt(jTextFieldTINHTRANG.getText(), jTablePHONG.getSelectedRow(), 5);
			model.setValueAt(comboBoxMANVP.getSelectedItem(), jTablePHONG.getSelectedRow(), 6);
			model.setValueAt(comboBoxMADVP.getSelectedItem(), jTablePHONG.getSelectedRow(), 7);

			Connection con = getConnection();
			try {
				// Táº¡o má»™t Ä‘á»‘i tÆ°á»£ng Ä‘á»ƒ thá»±c hiá»‡n cÃ´ng viá»‡c
				st = (Statement) con.createStatement();

				String query = String.format(
						"UPDATE Phong SET TENPHONG ='%s', LOAIPHONG = '%s' , GIAPHONG = %s ,CHUTHICH = '%s' , TINHTRANG ='%s' , MANV= '%s' , MADV= '%s' WHERE MAPHONG = '%s'",
						jTextFieldTENPHONG.getText(), comboBoxLOAIPHONG.getSelectedItem(), jTextFieldGIAPHONG.getText(),
						jTextFieldCHUTHICHP.getText(), jTextFieldTINHTRANG.getText(), maNV,
						maDV, jTextFieldMAPHONG.getText());

				System.out.println("sql : " + query);
				st.execute(query);
				hienThiDanhSachPhong();
				setEmptyAll();
			} catch (Exception ex) {
				System.out.println(ex.getMessage());
				JOptionPane.showMessageDialog(this, ex.getMessage());
//				ex.printStackTrace();
			}

		}
	}// GEN-LAST:event_sua3ActionPerformed

	private void xoa3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_xoa3ActionPerformed
		if(StringUtils.isEmpty(jTextFieldMAPHONG.getText())) {
			JOptionPane.showMessageDialog(this, "Vui lòng nhập mã phòng để xóa");
			return;
		}
		
		Connection con = getConnection();
		try {
			st = (Statement) con.createStatement();
			String query = "DELETE FROM phong WHERE MAPHONG = '" + jTextFieldMAPHONG.getText() + "'";
			st.executeUpdate(query);
			hienThiDanhSachPhong();
			setEmptyAll();
		} catch (Exception ex) {

			System.out.println(ex.getMessage());
			JOptionPane.showMessageDialog(this, ex.getMessage());
//			ex.printStackTrace();
		}

	}// GEN-LAST:event_xoa3ActionPerformed

	private void thoat3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_thoat3ActionPerformed
		// TODO add your handling code here:
		thoat3.setToolTipText("Click thoát chương trình ");
		int selected = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thoát chương trình" + " trên không",
				"Thông báo", JOptionPane.YES_NO_CANCEL_OPTION);
		if (selected == JOptionPane.YES_NO_OPTION) {
			this.dispose();

		}
	}// GEN-LAST:event_thoat3ActionPerformed

	private void jButtonclear3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonclear3ActionPerformed
		setEmptyAll();
		jTextFieldMAPHONG.requestFocus();
	}// GEN-LAST:event_jButtonclear3ActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(phongform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(phongform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(phongform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(phongform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new phongform().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButtonclear3;
	private javax.swing.JLabel jLabel22;
	private javax.swing.JLabel jLabel23;
	private javax.swing.JLabel jLabel24;
	private javax.swing.JLabel jLabel25;
	private javax.swing.JLabel jLabel26;
	private javax.swing.JLabel jLabel27;
	private javax.swing.JLabel jLabel28;
	private javax.swing.JLabel jLabel29;
	private javax.swing.JLabel jLabel30;
	private javax.swing.JPanel jPanel17;
	private javax.swing.JPanel jPanel18;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JTable jTablePHONG;
	private javax.swing.JTextField jTextFieldCHUTHICHP;
	private javax.swing.JTextField jTextFieldGIAPHONG;
	private javax.swing.JTextField jTextFieldMAPHONG;
	private javax.swing.JTextField jTextFieldTENPHONG;
	private javax.swing.JTextField jTextFieldTINHTRANG;
	private javax.swing.JButton sua3;
	private javax.swing.JButton them3;
	private javax.swing.JButton thoat3;
	private javax.swing.JButton xoa3;
	private JComboBox comboBoxLOAIPHONG;
	private JComboBox comboBoxMANVP;
	private JComboBox comboBoxMADVP;
	// End of variables declaration//GEN-END:variables

	private void setLocationDefault(int w, int h) {
		Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

		int x = (dim.width - w) / 2;
		int y = (dim.height - h) / 2;

		// Move the window
		this.setLocation(x, y);
	}

	private void setEmptyAll() {
		jTextFieldMAPHONG.setText("");
		jTextFieldTENPHONG.setText("");
		comboBoxLOAIPHONG.setSelectedIndex(0);
		jTextFieldGIAPHONG.setText("");
		jTextFieldCHUTHICHP.setText("");
		jTextFieldTINHTRANG.setText("");
		comboBoxMADVP.setSelectedIndex(0);
		comboBoxMANVP.setSelectedIndex(0);
	}

	private void loadComboxbo() {
		dsdv = dichVuControl.layDanhSachDichVu();
		dsnv = nhanVienControl.layDanhSachNhanVien();

		DefaultComboBoxModel<DichVu> comboBoxModelDVP = new DefaultComboBoxModel<>(
				dsdv.toArray(new DichVu[dsdv.size()]));
		comboBoxMADVP.setModel(comboBoxModelDVP);

		DefaultComboBoxModel<NhanVien> comboBoxModelNVP = new DefaultComboBoxModel<>(
				dsnv.toArray(new NhanVien[dsnv.size()]));
		comboBoxMANVP.setModel(comboBoxModelNVP);

	}

}
