/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlksk57;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.LayoutStyle;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;

import qlksk57.Form.dichvuform;
import qlksk57.Form.hoadonform;
import qlksk57.Form.khachhangform;
import qlksk57.Form.nhanvienform;
import qlksk57.Form.phongform;

/**
 *
 * @author khoa
 */
@SuppressWarnings("serial")
public class MenuForm extends JFrame {

	/**
	 * Creates new form MenuForm
	 */
	public MenuForm() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new JPanel();
		jButtonnhanvien = new JButton();
		jButton3 = new JButton();
		jButton1 = new JButton();
		jButton2 = new JButton();
		jButton4 = new JButton();
		jLabel1 = new JLabel();

		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(51, 255, 255));

		jButtonnhanvien.setBackground(new java.awt.Color(255, 255, 255));
		jButtonnhanvien.setIcon(new ImageIcon(getClass().getResource("/qlksk57/Form/hinh/enploy.png"))); // NOI18N
		jButtonnhanvien.setText("Nhân viên");
		jButtonnhanvien.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonnhanvienActionPerformed(evt);
			}
		});

		jButton3.setBackground(new java.awt.Color(255, 255, 255));
		jButton3.setIcon(new ImageIcon(getClass().getResource("/qlksk57/Form/hinh/sssssasasas.png"))); // NOI18N
		jButton3.setText("Dịch vụ");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jButton1.setBackground(new java.awt.Color(255, 255, 255));
		jButton1.setIcon(new ImageIcon(getClass().getResource("/qlksk57/Form/hinh/qqqqq.png"))); // NOI18N
		jButton1.setText("Phòng");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setBackground(new java.awt.Color(255, 255, 255));
		jButton2.setIcon(new ImageIcon(getClass().getResource("/qlksk57/Form/hinh/if_profile_3018530 (1).png"))); // NOI18N
		jButton2.setText("Khách hàng");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton4.setBackground(new java.awt.Color(255, 255, 255));
		jButton4.setIcon(new ImageIcon(getClass().getResource("/qlksk57/Form/hinh/sssssasasas.png"))); // NOI18N
		jButton4.setText("Dịch vụ");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 48)); // NOI18N
		jLabel1.setText("HOTEL  MANAGE");

		GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(26, 26, 26).addGroup(jPanel1Layout
						.createParallelGroup(GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
										.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 184,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(jButtonnhanvien))
								.addGap(44, 44, 44)
								.addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
										.addComponent(jButton2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(jButton3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE))
								.addGap(40, 40, 40))
						.addGroup(
								jPanel1Layout.createSequentialGroup()
										.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 375,
												GroupLayout.PREFERRED_SIZE)
										.addGap(36, 36, 36))))
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(145, 145, 145)
						.addComponent(jButton4, GroupLayout.PREFERRED_SIZE, 161, GroupLayout.PREFERRED_SIZE)
						.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(36, 36, 36).addComponent(jLabel1)
						.addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
										.addComponent(jButtonnhanvien).addGap(18, 18, 18))
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(18, 18, 18)
										.addComponent(jButton3).addPreferredGap(LayoutStyle.ComponentPlacement.RELATED,
												GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
						.addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
								.addComponent(jButton2).addComponent(jButton1))
						.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jButton4, GroupLayout.PREFERRED_SIZE, 51, GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));

		GroupLayout layout = new GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(jPanel1,
				GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(jPanel1,
				GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButtonnhanvienActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonnhanvienActionPerformed
		// TODO add your handling code here
		nhanvienform nvf = new nhanvienform();
		nvf.setVisible(true);
		nvf.pack();
		nvf.setLocationRelativeTo(null);
		nvf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
	}// GEN-LAST:event_jButtonnhanvienActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		// TODO add your handling code here:
		khachhangform khf = new khachhangform();
		khf.setVisible(true);
		khf.pack();
		khf.setLocationRelativeTo(null);
		khf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

	}// GEN-LAST:event_jButton2ActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code
		phongform pf = new phongform();
		pf.setVisible(true);
		pf.pack();
		pf.setLocationRelativeTo(null);
		pf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

	}// GEN-LAST:event_jButton1ActionPerformed

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
		// TODO add your handling code here
		hoadonform hdf = new hoadonform();
		hdf.setVisible(true);
		hdf.pack();
		hdf.setLocationRelativeTo(null);
		hdf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
	}// GEN-LAST:event_jButton4ActionPerformed

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
		// TODO add your handling code here:
		dichvuform dvf = new dichvuform();
		dvf.setVisible(true);
		dvf.pack();
		dvf.setLocationRelativeTo(null);
		dvf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
	}// GEN-LAST:event_jButton3ActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			Logger.getLogger(MenuForm.class.getName()).log(Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			Logger.getLogger(MenuForm.class.getName()).log(Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			Logger.getLogger(MenuForm.class.getName()).log(Level.SEVERE, null, ex);
		} catch (UnsupportedLookAndFeelException ex) {
			Logger.getLogger(MenuForm.class.getName()).log(Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MenuForm().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private JButton jButton1;
	private JButton jButton2;
	private JButton jButton3;
	private JButton jButton4;
	private JButton jButtonnhanvien;
	private JLabel jLabel1;
	private JPanel jPanel1;
	// End of variables declaration//GEN-END:variables
}
